version: '3.8'

networks:
  smart-city-net:
    driver: bridge

services:
  # ==========================================
  # BASES DE DONNÉES
  # ==========================================
  
  # 1. PostgreSQL (Mobility, Air, Auth)
  postgres-db:
    image: postgres:17-alpine
    container_name: smart-city-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1922
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart-city-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. MongoDB (Emergency, Energy)
  mongo-db:
    image: mongo:8.2.2
    container_name: smart-city-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo_data:/data/db
      - ./infrastructure/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - smart-city-net

  # 3. MySQL (Citizen)
  mysql-db:
    image: mysql:8.0
    container_name: smart-city-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=citizen_db
      - MYSQL_USER=citizen_user
      - MYSQL_PASSWORD=citizen1922
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart-city-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ==========================================
  # MICROSERVICES MÉTIERS
  # ==========================================

  # SERVICE 1 : SMART MOBILITY (REST)
  mobility-service:
    build: ./backend/mobility-service
    container_name: mobility-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mobility_db
      - SPRING_DATASOURCE_USERNAME=mobility_user
      - SPRING_DATASOURCE_PASSWORD=mobility1922
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - smart-city-net
    depends_on:
      postgres-db:
        condition: service_healthy

  # SERVICE 2 : AIR QUALITY (SOAP)
  air-quality-service:
    build: ./backend/air-quality-service
    container_name: air-quality-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/air_db
      - SPRING_DATASOURCE_USERNAME=air_user
      - SPRING_DATASOURCE_PASSWORD=air1922
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - smart-city-net
    depends_on:
      postgres-db:
        condition: service_healthy

  # SERVICE 3 : SMART EMERGENCY (gRPC)
  emergency-service:
    build: ./backend/emergency-service
    container_name: emergency-service
    ports:
      - "50053:50053"
    environment:
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=emergency_db
      - MONGO_USER=emergency_user
      - MONGO_PASS=emergency1922
    networks:
      - smart-city-net
    depends_on:
      - mongo-db

  # SERVICE 4 : SMART ENERGY (GraphQL)
  energy-service:
    build: ./backend/energy-service
    container_name: energy-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://energy_user:energy1922@mongo-db:27017/energy_db?authSource=energy_db
    networks:
      - smart-city-net
    depends_on:
      - mongo-db

  # SERVICE 5 : SMART CITIZEN (REST)
  citizen-service:
    build: ./backend/citizen-service
    container_name: citizen-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/citizen_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=citizen_user
      - SPRING_DATASOURCE_PASSWORD=citizen1922
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - smart-city-net
    depends_on:
      mysql-db:
        condition: service_healthy

  # ==========================================
  # SERVICES D'INFRASTRUCTURE & ORCHESTRATION
  # ==========================================

  # SERVICE 6 : AUTH SERVICE (Security)
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth1922
      - APPLICATION_SECURITY_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # Identifiants Admin par défaut
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin1922
    networks:
      - smart-city-net
    depends_on:
      postgres-db:
        condition: service_healthy

  # ORCHESTRATOR SERVICE (Le Cerveau)
  orchestrator-service:
    build: ./backend/orchestrator-service
    container_name: orchestrator-service
    ports:
      - "8084:8084"
    networks:
      - smart-city-net
    depends_on:
      - emergency-service
      - air-quality-service

  # API GATEWAY (Point d'entrée unique)
  api-gateway:
    build: ./infrastructure/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - smart-city-net
    depends_on:
      - auth-service
      - mobility-service
      - citizen-service
      - energy-service
      - orchestrator-service

  # ==========================================
  # FRONTEND (React)
  # ==========================================
  
  client:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80" # Accessible sur http://localhost:3000
    networks:
      - smart-city-net
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  mongo_data:
  mysql_data: